# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  # Our Phoenix container
  phoenix:
    # File with all the environment variables
    env_file:
      - .env
    volumes:
      - ./server/config:/app/config
      - ./server/entrypoints:/app/entrypoints
      - ./server/lib:/app/lib
      - ./server/priv:/app/priv
      - ./server/test:/app/test
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory
      context: ./server
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
  db:
    # We use the predefined Postgres image
    image: postgres:alpine
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build: ./client
    ports:
      - "3000:3000"
      - "3001:3001"
      - "3002:3002"
    depends_on:
        - phoenix
    volumes:
      - ./client/packages:/app/packages

  proxy:
    image: traefik:alpine
    command: --api --logLevel="DEBUG"
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - ./proxy/traefik.toml:/etc/traefik/traefik.toml

# Define the volumes
volumes:
  pgdata:
