version: '3'

services:
  phoenix:
    env_file:
      - .env
    volumes:
      - ./server/config:/app/config
      - ./server/entrypoints:/app/entrypoints
      - ./server/apps:/app/apps
    # The build parameters for this container.
    build: ./server
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend-immohub:
    build:
      context: ./client/immohub
      dockerfile: Dockerfile.dev
    depends_on:
        - phoenix
    volumes:
      - ./client/packages:/app/packages

  frontend-agency:
    build:
      context: ./client/agency
      dockerfile: Dockerfile.dev
    depends_on:
        - phoenix
    volumes:
      - ./client/packages:/app/packages

  proxy:
    image: traefik:alpine
    command: --api --logLevel="DEBUG"
    ports:
      - "5000:5000"
      - "8080:8080"
    volumes:
      - ./proxy/traefik.toml:/etc/traefik/traefik.toml

# Define the volumes
volumes:
  pgdata:
