logLevel = "INFO"

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":5000"


[file]

  [backends]

    [backends.api]
      [backends.api.servers.server1]
      url = "http://phoenix:4000"

    [backends.immohub]
      [backends.immohub.servers.server1]
      url = "http://frontend:3002"

    [backends.web_agency]
      [backends.web_agency.servers.server1]
      url = "http://frontend:3000"

    # when PUBLIC_PATH is ready for development
    # [backends.web_admin]
    #   [backends.web_admin.servers.server1]
    #   url = "http://frontend:3001"


  [frontends]

    [frontends.immohub]
    backend = "immohub"

    [frontends.api]
    backend = "api"
      [frontends.api.routes.test_1]
      rule = "Path:/api"

    [frontends.web_agency]
    backend = "web_agency"
      [frontends.web_agency.routes.test_1]
        rule = "HostRegexp:{subdomain:[a-z]+}.localhost"

    # when PUBLIC_PATH is ready for development
    # [frontends.web_admin]
    # backend = "web_admin"
    #   [frontends.web_admin.routes.test_1]
    #     rule = "HostRegexp:{subdomain:[a-z]+}.localhost"
    #   [frontends.web_admin.routes.test_2]
    #   rule = "Path:/admin"
