logLevel = "INFO"

defaultEntryPoints = ["http"]

[entryPoints]
  [entryPoints.http]
  address = ":5000"


[file]

  [backends]

    [backends.auth]
      [backends.auth.servers.server1]
      url = "http://phoenix:4001"

    [backends.client_api]
      [backends.client_api.servers.server1]
      url = "http://phoenix:4002"

    [backends.immohub]
      [backends.immohub.servers.server1]
      url = "http://frontend-immohub:3001"

    [backends.web_agency]
      [backends.web_agency.servers.server1]
      url = "http://frontend-agency:3000"


  [frontends]

    [frontends.immohub]
    backend = "immohub"

    [frontends.client_api]
    backend = "client_api"
      [frontends.client_api.routes.test_1]
      rule = "Path:/api"

    [frontends.auth]
    backend = "auth"
      [frontends.auth.routes.test_1]
      rule = "Path:/auth"

    [frontends.web_agency]
    backend = "web_agency"
      [frontends.web_agency.routes.test_1]
        rule = "HostRegexp:{subdomain:[a-z]+}.localhost"
